import { Pathway, Registration, Shell, WorkshopGrid } from "./components";

function JudgementMap(){return <div className="judgement-map" aria-hidden="true"><div className="map-orbit orbit-one"/><div className="map-orbit orbit-two"/><div className="map-core"><span>DECIDE</span><b>?</b></div><div className="branch branch-a"><i/><span>Trust</span></div><div className="branch branch-b"><i/><span>Evidence</span></div><div className="branch branch-c"><i/><span>Values</span></div><div className="branch branch-d"><i/><span>Responsibility</span></div><div className="branch branch-e"><i/><span>Uncertainty</span></div><div className="map-caption"><b>Judgement is not linear.</b><span>Evidence changes. Context shifts. Decisions remain human.</span></div></div>}

export default function ThinkLab(){return <Shell variant="landing-v2"><main id="content"><section className="hero hero-v2"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="hero-copy"><p className="eyebrow"><span/> ThinkLab™ · Proposed pilot</p><h1><span>Human</span> judgement, <em>made visible.</em></h1><p className="hook">AI can answer in seconds.<br/><b>Can you decide what deserves trust?</b></p><p className="intro">Six research-informed workshop experiences for students navigating decisions in an AI-enabled world.</p><div className="actions"><a className="button primary" href="#experiences">Explore the six experiences <span>↘</span></a><a className="button secondary" href="/thinklab/pilot">Pilot details: Coming soon</a></div><div className="hero-proof"><span><b>01</b> Paper-based</span><span><b>02</b> No technical background</span><span><b>03</b> Human decisions first</span></div></div><JudgementMap/><a className="scroll-cue" href="#method"><span>Scroll to investigate</span><i/></a></section>
<section className="section split method-v2" id="method"><div><p className="eyebrow">01 · The methodology</p><h2>Not better answers.<br/><em>Better judgement.</em></h2></div><div className="lead"><p>ThinkLab™ is a research-informed methodology for developing human judgement in AI-supported higher education. Through structured decisions, staged evidence, discussion and reflection, students practise deciding what deserves trust, what should remain human, what counts as sufficient evidence and how to act when certainty is impossible.</p><p>ThinkLab does not teach students to accept or reject AI automatically. It helps them make decisions they can explain, limit and revisit.</p></div></section>
<section className="principles principles-v2" aria-label="ThinkLab method"><article><b>01</b><div className="principle-mark">C</div><h3>Choose</h3><p>Make an initial judgement before hearing the room.</p></article><article><b>02</b><div className="principle-mark">L</div><h3>Look</h3><p>Examine the assumptions, evidence, values and consequences.</p></article><article><b>03</b><div className="principle-mark">↺</div><h3>Change</h3><p>Keep, revise or reverse the judgement for a clear reason.</p></article></section>
<section className="section why why-v2"><div className="why-kicker">THE SHIFT</div><p className="eyebrow">02 · Why now?</p><h2>Convincing is not the same as <em>trustworthy.</em></h2><div className="why-grid"><ul><li><b>01</b> Polished output can conceal weak reasoning.</li><li><b>02</b> Recommendations can ignore context.</li><li><b>03</b> Support can quietly become substitution.</li></ul><ul><li><b>04</b> Evidence can be overstated.</li><li><b>05</b> Values shape every reasonable choice.</li><li><b>06</b> Uncertainty does not remove responsibility.</li></ul></div><blockquote><span>“Can AI do this?”</span><b>is only the beginning.</b><em>What should the human decide—and why?</em></blockquote></section>
<section className="section experiences-v2" id="experiences"><div className="section-intro"><div><p className="eyebrow">03 · The programme</p><h2>Six experiences.<br/><em>One developing judgement.</em></h2></div><p>Each lab isolates a different pressure on human decision-making. Together, they build a practical discipline for choices that can be explained and revisited.</p></div><WorkshopGrid/></section>
<section className="section process process-v2"><p className="eyebrow">04 · Inside a session</p><h2>A decision is only<br/>the <em>first move.</em></h2><Pathway/><p className="process-note">There is not always one teacher-approved answer. Students make a defensible judgement and show what would make them reconsider it.</p></section>
<section className="section future future-v2"><div><p className="eyebrow">05 · Beyond the proposed pilot</p><h2>Paper before <em>platform.</em></h2></div><div><p>A proposed pilot, subject to institutional approval, would be the first stage in the classroom validation of ThinkLab. If approved, evidence from student work, facilitator observation and participant experience would inform refinement before any wider implementation.</p><p>Digital development will proceed only where technology creates a clear educational advantage—not merely reproduce paper activities on screen.</p><a className="text-link" href="/thinklab/research">Explore research and development →</a></div></section><Registration/></main></Shell>}
